export default {
    RESET: 'RESET',

    CACHE_RECIPE: 'CACHE_RECIPE',
    CACHE_SEARCH: 'CACHE_SEARCH',

    ADD_WANT_GROCERY: 'ADD_WANT_GROCERY',
    REMOVE_WANT_GROCERY: 'REMOVE_WANT_GROCERY',
    SET_WANT_GROCERIES: 'SET_WANT_GROCERIES',
    ADD_HAVE_GROCERY: 'ADD_HAVE_GROCERY',
    REMOVE_HAVE_GROCERY: 'REMOVE_HAVE_GROCERY',
    SET_HAVE_GROCERIES: 'SET_HAVE_GROCERIES',

    UNSAVE_RECIPE: 'UNSAVE_RECIPE',
    SAVE_RECIPE: "SAVE_RECIPE",

    USERNAME: 'USERNAME',
    EMAIL: "EMAIL",

    SET_FILTER: 'SET_FILTER',

    ADD_SEARCH_HISTORY: 'ADD_SEARCH_HISTORY',
    ADD_FOOD_HISTORY: 'ADD_FOOD_HISTORY',

    CREATE_LIST: 'CREATE_LIST',
    ADD_TO_LIST: 'ADD_TO_LIST',

    SET_RATING: 'SET_RATING',

    PLAN_FOOD: 'PLAN_FOOD',
    REMOVE_PLAN: 'REMOVE_PLAN'
};
