export default {
    RESET: 'RESET',

    CACHE_RECIPE: 'CACHE_RECIPE',
    CACHE_SEARCH: 'CACHE_SEARCH',

    SET_GROCERY: "SET_GROCERY",
    REMOVE_GROCERY: 'REMOVE_GROCERY',
    OVERWRITE_GROCERIES: 'OVERWRITE_GROCERIES',

    UNSAVE_RECIPE: 'UNSAVE_RECIPE',
    SAVE_RECIPE: "SAVE_RECIPE",

    USERNAME: 'USERNAME',
    EMAIL: "EMAIL",

    SET_FILTER: 'SET_FILTER',

    ADD_SEARCH_HISTORY: 'ADD_SEARCH_HISTORY',
    ADD_FOOD_HISTORY: 'ADD_FOOD_HISTORY',

    CREATE_LIST: 'CREATE_LIST',
    ADD_TO_LIST: 'ADD_TO_LIST',

    ADD_EVENT: "ADD_EVENT",
    REMOVE_EVENT: 'REMOVE_EVENT',
};
